spring.application.name=product-service
# Use the NEW Spring Boot 3 prefix (remove '.data')
spring.mongodb.uri=mongodb://root:password@localhost:27017/product-service?authSource=admin
#Api Documentation
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs